// Test modules
mod tests_semantic_token_all_constructs;
mod tests_semantic_token_collector_normalize_path;
mod tests_semantic_token_collector_semantictokencollector;
mod tests_semantic_token_positions;
mod tests_semantic_token_text_extraction;
